workflows:
  android-release:
    name: Flutter Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      java: 21
      groups:
        - google_credentials 
      
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.pub-cache
        
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
          
    scripts:
      - name: Preparar ambiente
        script: |
          mkdir -p "$CM_BUILD_DIR/android/gradle/wrapper"
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Forçar Gradle 8.14 no wrapper (Correção do erro)
        script: |
          echo "distributionBase=GRADLE_USER_HOME" > "$CM_BUILD_DIR/android/gradle/wrapper/gradle-wrapper.properties"
          echo "distributionPath=wrapper/dists" >> "$CM_BUILD_DIR/android/gradle/wrapper/gradle-wrapper.properties"
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.14-all.zip" >> "$CM_BUILD_DIR/android/gradle/wrapper/gradle-wrapper.properties"
          echo "networkTimeout=10000" >> "$CM_BUILD_DIR/android/gradle/wrapper/gradle-wrapper.properties"
          echo "validateDistributionUrl=true" >> "$CM_BUILD_DIR/android/gradle/wrapper/gradle-wrapper.properties"
          echo "zipStoreBase=GRADLE_USER_HOME" >> "$CM_BUILD_DIR/android/gradle/wrapper/gradle-wrapper.properties"
          echo "zipStorePath=wrapper/dists" >> "$CM_BUILD_DIR/android/gradle/wrapper/gradle-wrapper.properties"

      - name: Adicionar flags de compatibilidade ao gradle.properties
        script: |
          echo "android.newDsl=false" >> "$CM_BUILD_DIR/android/gradle.properties"
          echo "android.builtInKotlin=false" >> "$CM_BUILD_DIR/android/gradle.properties"

      - name: Criar google-services.json
        script: |
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo $GOOGLE_SERVICES_JSON > "$CM_BUILD_DIR/android/app/google-services.json"
          else
            echo "Aviso: GOOGLE_SERVICES_JSON não está definido."
          fi

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
